import type { DocPageData } from "../../shared";

export const playgroundENDoc: DocPageData = {
    slug: "playground", navLabel: "Playground", eyebrow: "Playground (Provisional)", heading: "Playground Guide (Provisional)", title: "Cmd+kit | Playground Docs",
    description: "Learn how to use the Cmd+kit playground to configure commands, preview behavior, and export production-ready starter code.",
    intro: ["This guide is <strong>provisional</strong> and will be finalized after the playground UX and exports are fully closed. The final version will include real screenshots and step-by-step production flows.", "The playground is the fastest way to shape a <code>Cmd+kit</code> integration before moving the result into your codebase. It lets you configure the command model, test the interaction flow in a live preview, and export starter code for the supported adapters."],
    sections: [
      { id: "what-the-playground-is-for", label: "What the playground is for", blocks: [{ type: "list", items: ["prototype your command palette structure without editing source files first", "test nested navigation, search behavior, and command grouping in real time", "adjust theme tokens and copy before integrating the package", "export starter snippets for React, Vue, Preact, vanilla browser code, CSS, Tailwind, and JSON"] }] },
      { id: "main-areas", label: "Main areas", blocks: [{ type: "list", items: ["<strong>Basics</strong>: title, keyboard shortcut, source mode, and high-level settings", "<strong>Sections</strong>: create groups of commands and edit each item", "<strong>Nested commands</strong>: add child sections to model drill-down navigation", "<strong>Messages</strong>: customize placeholder, empty state, and related UI copy", "<strong>Theme</strong>: tune accent, surface, border, text, radius, and shadow values", "<strong>Preview</strong>: validate the interaction and keyboard flow live", "<strong>Code</strong>: export the current config in the format you need"] }] },
      { id: "how-to-work-with-it", label: "How to work with it", blocks: [{ type: "list", ordered: true, items: ["Start by defining your root sections and the commands inside each one.", "Add shortcuts, links, subtitles, and keywords where they improve discoverability.", "Create nested sections for flows that should drill into a second level.", "Adjust messages and theme tokens until the preview matches your product.", "Switch the export target and copy the generated starter code into your app."] }] },
      { id: "source-modes", label: "Source modes", blocks: [{ type: "paragraph", html: "The playground supports both static and async-style configuration. Use static mode to model inline sections. Use async mode when your final integration will load commands from an API or another runtime source and you want to verify loading behavior earlier." }] },
      { id: "exports", label: "Exports", blocks: [{ type: "paragraph", html: "The generated code is meant to be a practical starting point, not a locked template. Treat the export as a base integration and then refine naming, styles, and app-specific behavior inside your codebase." }] },
      { id: "common-mistakes", label: "Common mistakes", blocks: [{ type: "list", items: ["trying to model every command in detail before validating the top-level structure", "treating generated code as untouchable instead of adapting it to your project", "using the playground as package API documentation instead of pairing it with the adapter docs"] }] },
      { id: "best-practice", label: "Best practice", blocks: [{ type: "paragraph", html: "Use the playground to converge on structure and configuration quickly, then move to the package documentation pages for production API details. The playground accelerates onboarding; the docs remain the source of truth." }] },
      { id: "faq", label: "FAQ", blocks: [{ type: "list", items: ["<strong>Should I ship exported code without changes?</strong> Usually no. Treat exports as a starting scaffold and adapt naming, styling, and behavior to your production codebase.", "<strong>Is the playground the source of truth for API details?</strong> No. Use package docs (React, Vue, Preact, Astro, Core) as the source of truth for supported props and behavior.", "<strong>Can I use the playground if I plan to build on Core?</strong> Yes. It is useful for validating command structure before implementing custom rendering.", "<strong>Why does exported code differ slightly from my project style?</strong> Exports are intentionally generic. Normalize them to your lint rules, architecture, and design system conventions.", "<strong>What should I validate before moving playground output to production?</strong> Verify keyboard flow, nested navigation, accessibility labels, and async/error behavior in your real app context."] }] }
    ]
  };
