import type { DocPageData } from "../../shared";

export const playgroundESDoc: DocPageData = {
    slug: "playground", navLabel: "Playground", eyebrow: "Playground (Provisional)", heading: "Guía del playground (Provisional)", title: "Cmd+kit | Documentación del playground",
    description: "Aprende a usar el playground de Cmd+kit para configurar comandos, validar el comportamiento y exportar código base para producción.",
    intro: ["Esta guía es <strong>provisional</strong> y se cerrará cuando el playground esté terminado a nivel de UX y exports. La versión final incluirá capturas reales y flujos completos para producción.", "El playground es la forma más rápida de definir una integración con <code>Cmd+kit</code> antes de llevarla a tu código. Te permite configurar la estructura de comandos, validar el flujo en una preview viva y exportar código base para los adaptadores soportados."],
    sections: [
      { id: "para-que-sirve", label: "Para qué sirve", blocks: [{ type: "list", items: ["prototipar la estructura de la command palette sin editar ficheros de código al principio", "probar navegación anidada, búsqueda y agrupación en tiempo real", "ajustar tokens de tema y copy antes de integrar el paquete", "exportar snippets base para React, Vue, Preact, navegador vanilla, CSS, Tailwind y JSON"] }] },
      { id: "areas-principales", label: "Áreas principales", blocks: [{ type: "list", items: ["<strong>Basics</strong>: título, atajo, modo de source y ajustes generales", "<strong>Sections</strong>: creación de grupos de comandos y edición de cada ítem", "<strong>Nested commands</strong>: secciones hijas para modelar navegación en profundidad", "<strong>Messages</strong>: personalización del placeholder y del estado vacío", "<strong>Theme</strong>: ajuste de colores, borde, texto, radio y sombra", "<strong>Preview</strong>: validación en vivo de interacción y teclado", "<strong>Code</strong>: exportación de la configuración al formato que necesites"] }] },
      { id: "como-trabajar-con-el", label: "Cómo trabajar con él", blocks: [{ type: "list", ordered: true, items: ["Define primero las secciones raíz y los comandos de cada una.", "Añade atajos, enlaces, subtítulos y keywords cuando aporten claridad.", "Crea secciones anidadas para los flujos que necesiten un segundo nivel.", "Ajusta mensajes y tokens de tema hasta que la preview encaje con tu producto.", "Cambia el target de exportación y lleva el código generado a tu aplicación."] }] },
      { id: "modos-de-source", label: "Modos de source", blocks: [{ type: "paragraph", html: "El playground soporta configuración estática y configuración orientada a carga asíncrona. Usa el modo estático para modelar secciones inline. Usa el modo async cuando tu integración final vaya a cargar comandos desde una API o desde otra fuente dinámica." }] },
      { id: "exports", label: "Exports", blocks: [{ type: "paragraph", html: "El código generado está pensado como punto de partida práctico, no como plantilla cerrada. Lo normal es exportarlo, integrarlo en tu proyecto y seguir refinándolo según tu naming, estilos y comportamiento real." }] },
      { id: "buena-practica", label: "Buena práctica", blocks: [{ type: "paragraph", html: "Usa el playground para cerrar estructura y configuración rápidamente, y después apóyate en la documentación de los paquetes para la integración final. El playground acelera diseño y onboarding; la documentación sigue siendo la fuente de verdad para la API." }] },
      { id: "faq", label: "FAQ", blocks: [{ type: "list", items: ["<strong>¿Debo llevarme el código exportado tal cual a producción?</strong> Normalmente no. Úsalo como base y adáptalo a tu arquitectura, naming y estilos.", "<strong>¿El playground es la referencia oficial de API?</strong> No. La referencia oficial está en la documentación de cada paquete (React, Vue, Preact, Astro y Core).", "<strong>¿Tiene sentido usar playground si voy a implementar sobre Core?</strong> Sí. Es útil para validar primero la estructura de comandos antes de montar tu render custom.", "<strong>¿Por qué el snippet exportado no coincide al 100% con mi estilo de proyecto?</strong> Porque el export está diseñado como plantilla neutral. Ajusta formato, estructura y convenciones internas.", "<strong>¿Qué debería validar antes de pasar del playground a producción?</strong> Flujo de teclado, navegación anidada, labels de accesibilidad y comportamiento de carga/error en tu contexto real."] }] }
    ]
  };
