import type { Language } from "./config";

export type PlaygroundLabels = (typeof playgroundLabels)[Language];

export const playgroundLabels = {
  en: {
    config: "Configurator",
    preview: "Live Preview",
    code: "Generated Code",
    reactCode: "React",
    vueCode: "Vue",
    preactCode: "Preact",
    vanillaCode: "Vanilla JS",
    cssCode: "CSS Variables",
    tailwindCode: "Tailwind",
    jsonCode: "JSON",
    language: "Language",
    title: "Palette title",
    description: "Preview description",
    recents: "Recent items",
    recentsTitle: "Recent title",
    recentsLimit: "Recent limit",
    placeholder: "Search placeholder",
    noResults: "Empty state",
    closeLabel: "Close label",
    accent: "Accent color",
    surface: "Surface color",
    text: "Text color",
    muted: "Muted color",
    border: "Border color",
    overlay: "Overlay color",
    radius: "Radius",
    shadow: "Shadow",
    shortcut: "Shortcut",
    sections: "Sections",
    sectionTitle: "Section title",
    itemTitle: "Item title",
    itemSubtitle: "Item subtitle",
    itemIcon: "Item icon",
    itemShortcut: "Item shortcut",
    itemHref: "Item href",
    itemKeywords: "Item keywords",
    itemDisabled: "Disabled",
    nested: "Nested commands",
    nestedSectionTitle: "Nested section title",
    addNestedSection: "Add nested section",
    addNestedItem: "Add nested item",
    addSection: "Add section",
    addItem: "Add item",
    moveUp: "Move up",
    moveDown: "Move down",
    remove: "Remove",
    layout: "Layout",
    centered: "Centered",
    wide: "Wide",
    copy: "Copy",
    launch: "Open preview"
  },
  es: {
    config: "Configurador",
    preview: "Vista previa",
    code: "Codigo generado",
    reactCode: "React",
    vueCode: "Vue",
    preactCode: "Preact",
    vanillaCode: "Vanilla JS",
    cssCode: "Variables CSS",
    tailwindCode: "Tailwind",
    jsonCode: "JSON",
    language: "Idioma",
    title: "Titulo del palette",
    description: "Descripcion de preview",
    recents: "Items recientes",
    recentsTitle: "Titulo de recientes",
    recentsLimit: "Limite de recientes",
    placeholder: "Placeholder de busqueda",
    noResults: "Estado vacio",
    closeLabel: "Etiqueta de cierre",
    accent: "Color de acento",
    surface: "Color de fondo",
    text: "Color del texto",
    muted: "Color secundario",
    border: "Color del borde",
    overlay: "Color del overlay",
    radius: "Radio",
    shadow: "Sombra",
    shortcut: "Atajo",
    sections: "Secciones",
    sectionTitle: "Titulo de seccion",
    itemTitle: "Titulo del item",
    itemSubtitle: "Subtitulo del item",
    itemIcon: "Icono del item",
    itemShortcut: "Atajo del item",
    itemHref: "Href del item",
    itemKeywords: "Keywords del item",
    itemDisabled: "Deshabilitado",
    nested: "Comandos anidados",
    nestedSectionTitle: "Titulo de seccion anidada",
    addNestedSection: "Anadir seccion anidada",
    addNestedItem: "Anadir item anidado",
    addSection: "Anadir seccion",
    addItem: "Anadir item",
    moveUp: "Subir",
    moveDown: "Bajar",
    remove: "Eliminar",
    layout: "Layout",
    centered: "Centrado",
    wide: "Ancho",
    copy: "Copiar",
    launch: "Abrir preview"
  }
} satisfies Record<Language, Record<string, string>>;
