import type { Language } from "./config";

export const playgroundLabels = {
  en: {
    config: "Configurator",
    preview: "Live Preview",
    code: "Generated Code",
    reactCode: "React",
    cssCode: "CSS Variables",
    tailwindCode: "Tailwind",
    language: "Language",
    title: "Hero title",
    description: "Hero description",
    placeholder: "Search placeholder",
    noResults: "Empty state",
    accent: "Accent color",
    surface: "Surface color",
    text: "Text color",
    border: "Border color",
    radius: "Radius",
    shortcut: "Shortcut",
    sections: "Sections",
    sectionTitle: "Section title",
    itemTitle: "Item title",
    itemSubtitle: "Item subtitle",
    itemIcon: "Item icon",
    itemShortcut: "Item shortcut",
    itemHref: "Item href",
    itemKeywords: "Item keywords",
    itemDisabled: "Disabled",
    addSection: "Add section",
    addItem: "Add item",
    remove: "Remove",
    layout: "Layout",
    centered: "Centered",
    wide: "Wide",
    copy: "Copy",
    launch: "Open preview"
  },
  es: {
    config: "Configurador",
    preview: "Vista previa",
    code: "Codigo generado",
    reactCode: "React",
    cssCode: "Variables CSS",
    tailwindCode: "Tailwind",
    language: "Idioma",
    title: "Titulo principal",
    description: "Descripcion principal",
    placeholder: "Placeholder de busqueda",
    noResults: "Estado vacio",
    accent: "Color de acento",
    surface: "Color de fondo",
    text: "Color del texto",
    border: "Color del borde",
    radius: "Radio",
    shortcut: "Atajo",
    sections: "Secciones",
    sectionTitle: "Titulo de seccion",
    itemTitle: "Titulo del item",
    itemSubtitle: "Subtitulo del item",
    itemIcon: "Icono del item",
    itemShortcut: "Atajo del item",
    itemHref: "Href del item",
    itemKeywords: "Keywords del item",
    itemDisabled: "Deshabilitado",
    addSection: "Anadir seccion",
    addItem: "Anadir item",
    remove: "Eliminar",
    layout: "Layout",
    centered: "Centrado",
    wide: "Ancho",
    copy: "Copiar",
    launch: "Abrir preview"
  }
} satisfies Record<Language, Record<string, string>>;

